import { Theme } from '@emotion/react'
import { SvgIcon, SxProps } from '@mui/material'

export const UnipuckIcon = ({ sx }: { sx?: SxProps<Theme> }) => {
    return (
        <SvgIcon
            viewBox='0 0 24 24'
            sx={sx}
        >
            <svg
                focusable='false'
                aria-hidden='true'
                viewBox='-5 -5 110 110'
            >
                <circle
                    cx='50'
                    cy='50'
                    r='50'
                    fill='currentColor'
                    opacity='0.08'
                ></circle>
                <circle
                    cx='50'
                    cy='50'
                    r='50'
                    fill='none'
                    stroke='currentColor'
                    stroke-width='5'
                ></circle>
                <circle
                    cx='50'
                    cy='14'
                    r='6.9'
                    fill='currentColor'
                ></circle>
                <circle
                    cx='71.2'
                    cy='20.5'
                    r='6.9'
                    fill='currentColor'
                ></circle>
                <circle
                    cx='85.1'
                    cy='37.5'
                    r='6.9'
                    fill='currentColor'
                ></circle>
                <circle
                    cx='85.1'
                    cy='62.5'
                    r='6.9'
                    fill='currentColor'
                ></circle>
                <circle
                    cx='71.2'
                    cy='79.5'
                    r='6.9'
                    fill='currentColor'
                ></circle>
                <circle
                    cx='50'
                    cy='86'
                    r='6.9'
                    fill='currentColor'
                ></circle>
                <circle
                    cx='28.8'
                    cy='79.5'
                    r='6.9'
                    fill='currentColor'
                ></circle>
                <circle
                    cx='14.9'
                    cy='62.5'
                    r='6.9'
                    fill='currentColor'
                ></circle>
                <circle
                    cx='14.9'
                    cy='37.5'
                    r='6.9'
                    fill='currentColor'
                ></circle>
                <circle
                    cx='28.8'
                    cy='20.5'
                    r='6.9'
                    fill='currentColor'
                ></circle>
                <circle
                    cx='50'
                    cy='34'
                    r='6.9'
                    fill='currentColor'
                ></circle>
                <circle
                    cx='65.2'
                    cy='45.1'
                    r='6.9'
                    fill='currentColor'
                ></circle>
                <circle
                    cx='59.4'
                    cy='62.9'
                    r='6.9'
                    fill='currentColor'
                ></circle>
                <circle
                    cx='40.6'
                    cy='62.9'
                    r='6.9'
                    fill='currentColor'
                ></circle>
                <circle
                    cx='34.8'
                    cy='45.1'
                    r='6.9'
                    fill='currentColor'
                ></circle>
            </svg>
        </SvgIcon>
    )
}
